logger_params:
  name_base: "VI_ATCN_test"
  name_fields:  !!python/tuple [[train_params,learning_rate]] #!!python/tuple [[net_params,num_blocks],[net_params,block_size],[net_params,dilation_base],[net_params,window_size]]
  tags: !!python/tuple [webcorpus_2,VI,A-TCN,diacritics,residual]
  accuracy_types: !!python/tuple [chr, imp_chr, alpha_word, amb_word, sntnc]
  accuracy_plot_dashes: !!python/tuple [dotted,dotted,dashed,dashed,solid]
  benchmarks: !!python/tuple [{"soft_deaccent":{"keep_rate": 0.2}}, {"deaccent": null}]
  neptune_logging: true
  #baselines: !!python/tuple [hunaccent]
  #endplot_extend_from: /data/csbalint/logs/2021-03-25/15-49-00_webcorpus_2_TCN/
  #draw_network: true
data_params:
  language: "VI" # HU, PL, CZ, SK, VI

  file_path: ../webcorpus_2/VN_tmp
  file_type: txt_dir
  data_cut_rate: 0

  max_length: 0
  fixed_batch_lengths: false
  
  charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,?!();:-%&=+/\\\"' \nÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđ"
  lower_case: true
  pad_char: _
  unk_char: '*'
  mask_char: '#'

  random_seed: 42

  sort_data_by_length: true
  train_rate: 0.8
  vocabThreshold: 50
  batch_limit: 500

net_params:
  model_state_dict_path: #/data/csbalint/logs/diacritics/2021-10-20/21-22-10_Naplava_hun_TCN/1_Naplava_hun_TCN/model/best_on_dev.pt
  fname: BalU-Net.py
  embedding_dim: 32
  seq2seq_in_channels: 256
  dropout: 0.1
  spatial_dropout: false
  batch_norm: true

  padding_mode: zeros
  residual_type: sum
  residual_proj: false
  ATCN_structure:
    num_blocks: 4
    block_size: 3
    dilation_base: 2
    window_size: 5
    dilation_only_at_first: true
  SENet_r: null
  ECA_Net: false
  activation:
    name: ReLU

train_params:
  batch_size: 150
  early_stopping_delta: 0
  early_stopping_window: 20
  early_stopping_start: 50
  epochs: 100
  gradient_accumulation_steps: 1
  infer_batch_size: 50
  learning_rate:
    - 0.001
    - 0.0001
  loss_fn: cross_entropy
  parallel: true
  save_final_model: false
  eval_batch_limit: 50
  augmentations:
    soft_deaccent:
      keep_rate: 0.2
wrong_examples_nmbr: 0
